name:                picalc
version:             0.1.0.0
github:              "githubuser/picalc"
license:             BSD3
author:              "Ki Yung Ahn"
maintainer:          "kyagrd@gmail.com"
copyright:           "2019 Ki Yung Ahn"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/picalc#readme>

dependencies:
- base >= 4.7 && < 5
- unbound-generics
- lens
- uglymemo
- containers
- transformers
- data-partition
- tree-view
# - bimap

library:
  source-dirs: src

executables:
  picalc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - picalc

tests:
  picalc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - picalc
